# Generated by Django 6.0 on 2025-12-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.CharField(default=2025, max_length=200),
            preserve_default=False,
        ),
    ]
